### ISSUE TITLE
SwiftyBeaver

### ISSUE THREAD

**Issue by IsaiahJTurner** [netceteragroup/GirdersSwift#22]
Your project uses SwiftyBeaver. SwiftyBeaver has security vulnerabilities that you may wish to address. Consider removing SwiftyBeaver if your app transmits PII. https://github.com/SwiftyBeaver/SwiftyBeaver/issues/453

**Comment by martinmitrevski** [comment]
We're not using SwiftyBeaver for sending logs to a server.
